// Zuordnung Emoji → Symbol. Die Daten (Routinen, Schritte, gespeicherte
// Kunden-Routinen) behalten ihr Emoji; nur die Anzeige wechselt aufs Symbol.
// null = bewusst ohne Bild (nur Text). Nicht aufgeführt = Emoji bleibt.

import type { SymbolName } from "@/components/icons/TagSymbole";

const ZUORDNUNG: Record<string, SymbolName | null> = {
  "💊": "medikament",
  "🪥": "zahnbuerste",
  "🚿": "dusche",
  "🛁": "dusche",
  "🧴": "pflege",
  "💄": "pflege",
  "☀": "pflege",
  "🚻": "toilette",
  "👕": "kleidung",
  "👔": "kleidung",
  "🎩": "kleidung",
  "🧣": "kleidung",
  "🧦": "kleidung",
  "🧺": "waeschekorb",
  "🧥": "jacke",
  "💧": "wasser",
  "🥤": "wasser",
  "🍱": "snack",
  "🥨": "snack",
  "🍌": "snack",
  "🥪": "snack",
  "🍎": "snack",
  "🥜": "snack",
  "🧀": "snack",
  "🍯": "snack",
  "🍽": "essen",
  "🥗": "essen",
  "🍞": "fruehstueck",
  "🍳": "fruehstueck",
  "☕": "kaffee",
  "🛒": "einkaufswagen",
  "🛏": "bett",
  "🛌": "bett",
  "⏱": "uhr",
  "🕐": "uhr",
  "⏳": "uhr",
  "💡": "licht",
  "🔦": "licht",
  "🌅": "morgen",
  "🌞": "morgen",
  "🔆": "morgen",
  "🌙": "abend",
  "🌆": "abend",
  "⏰": "wecker",
  "😴": "schlafen",
  "🎒": "rucksack",
  "💼": "rucksack",
  "🧳": "rucksack",
  "📋": "liste",
  "📝": "liste",
  "📓": "liste",
  "📔": "liste",
  "📖": "buch",
  "📚": "buch",
  "✅": "erledigt",
  "✏": "stift",
  "✍": "stift",
  "📅": "kalender",
  "🗓": "kalender",
  "💻": "computer",
  "🖥": "computer",
  "🌐": "computer",
  "🎯": "ziel",
  "📱": "handy",
  "📞": "handy",
  "🌦": "wetter",
  "🌤": "wetter",
  "🌧": "wetter",
  "❄": "wetter",
  "🔑": "schluessel",
  "🔒": "schluessel",
  "🚪": "tuer",
  "🚗": "auto",
  "🚚": "auto",
  "🚦": "auto",
  "🔌": "laden",
  "🔋": "laden",
  "🌲": "natur",
  "🌳": "natur",
  "🍂": "natur",
  "🌿": "natur",
  "⛰": "natur",
  "🏠": "haus",
  "🛖": "haus",
  "🏕": "haus",
  "🎧": "kopfhoerer",
  "🎵": "kopfhoerer",
  "🎙": "kopfhoerer",
  "💵": "geld",
  "💰": "geld",
  "📦": "kiste",
  "🧹": "aufraeumen",
  "🪣": "aufraeumen",
  "🧽": "aufraeumen",
  "🛋": "sofa",
  "🚶": "gehen",
  "🧘": "atmen",
  "😮‍💨": "atmen",
  "🦘": "bewegungspause",
  "🦵": "bewegungspause",
  "👀": "bewegungspause",
  "🧍": "bewegungspause",
  "✊": "bewegungspause",
  "🙇": "bewegungspause",
  "🤲": "bewegungspause",
  "💃": "bewegungspause",
  "🏃": "sport",
  "🏋": "sport",
  "💪": "sport",
  "🤸": "dehnen",
  "🙆": "dehnen",
  "🙌": "dehnen",
  "⭐": "belohnung",
  "🌟": "belohnung",
  "✨": "belohnung",
  "🏆": "belohnung",
  "🏅": "belohnung",
  "💎": "belohnung",
  "🎉": "belohnung",
  "👍": "belohnung",
  "👥": "familie",
  "👨‍👩‍👧": "familie",
  "👶": "familie",
  "🤝": "familie",
  "👋": "familie",
  "🧠": "kopf",
  "🤔": "kopf",
  "❓": "kopf",
  "🤷": "kopf",
  "⚖": "kopf",
  "🙂": "person",
  "👤": "person",
  "🎁": "geschenk",
  "🎂": "geschenk",
  "🎗": "geschenk",
  "📄": "dokument",
  "📑": "dokument",
  "📂": "dokument",
  "🗂": "dokument",
  "🧾": "dokument",
  "🖨": "dokument",
  "📥": "dokument",
  "🏷": "dokument",
  "📬": "post",
  "📮": "post",
  "✉": "post",
  "💌": "post",
  "👟": "schuhe",
  "🥾": "schuhe",
  "🎫": "ausweis",
  "🪪": "ausweis",
  "🛂": "ausweis",
  "💳": "ausweis",
  "🗺": "karte",
  "📍": "karte",
  "🧭": "karte",
  "🗑": "muell",
  "🌡": "heizung",
  "🔥": "heizung",
  "💬": "nachricht",
  "🗣": "nachricht",
  "🩺": "erste_hilfe",
  "🩹": "erste_hilfe",
  "😷": "erste_hilfe",
  "🕶": "brille",
  "🚊": "oev",
  "🚌": "oev",
  "🪟": "fenster",
  "📷": "foto",
  "📸": "foto",
  "🖼": "foto",
  "💇": "pflege",
  "🧼": "pflege",
  "🦟": "pflege",
  "💍": "kleidung",
  "🪡": "kleidung",
  "🐕": "haus",
  "🐈": "haus",
  "🪴": "natur",
  "🛑": "atmen",
  "🧊": "atmen",
  "🌫": "sofa",
  "⚡": "uhr",
  "🍅": "uhr",
  "🪶": null,
  "🐾": null,
  "🐘": null,
  "🎮": "belohnung",
  "🔁": "kiste",
  "📊": "kopf",
  "🏛": "dokument",
  "👆": "ausweis",
  "📯": "erste_hilfe",
  "🏃‍♂": "sport",
};

const ohneVariante = (emoji: string) => emoji.replace(/\uFE0F/g, "").trim();

/** Symbolname, null (bewusst kein Bild) oder undefined (unbekannt → Emoji zeigen). */
export function symbolFuer(emoji: string | null | undefined): SymbolName | null | undefined {
  if (!emoji) return undefined;
  const e = ohneVariante(emoji);
  if (e in ZUORDNUNG) return ZUORDNUNG[e];
  // Zusammengesetzte Emoji (z. B. mit Hautton oder Geschlecht): erstes Zeichen zählt.
  const erstes = Array.from(e)[0];
  if (erstes && erstes in ZUORDNUNG) return ZUORDNUNG[erstes];
  return undefined;
}

/** false nur dort, wo bewusst kein Bild gezeigt wird. */
export function zeigtBild(emoji: string | null | undefined): boolean {
  return !!emoji && symbolFuer(emoji) !== null;
}
