/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerbindenRouteImport } from './routes/verbinden'
import { Route as StatistikenRouteImport } from './routes/statistiken'
import { Route as RuheRouteImport } from './routes/ruhe'
import { Route as RoutinenRouteImport } from './routes/routinen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EntscheidenRouteImport } from './routes/entscheiden'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunWorkflowIdRouteImport } from './routes/run.$workflowId'
import { Route as RuheExerciseIdRouteImport } from './routes/ruhe.$exerciseId'
import { Route as RoutinenNeuRouteImport } from './routes/routinen.neu'
import { Route as RoutinenWorkflowIdRouteImport } from './routes/routinen.$workflowId'
import { Route as EntscheidenHelperIdRouteImport } from './routes/entscheiden.$helperId'
import { Route as RoutinenBibliothekSlugRouteImport } from './routes/routinen.bibliothek.$slug'
import { Route as RoutinenWorkflowIdBearbeitenRouteImport } from './routes/routinen.$workflowId.bearbeiten'

const VerbindenRoute = VerbindenRouteImport.update({
  id: '/verbinden',
  path: '/verbinden',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistikenRoute = StatistikenRouteImport.update({
  id: '/statistiken',
  path: '/statistiken',
  getParentRoute: () => rootRouteImport,
} as any)
const RuheRoute = RuheRouteImport.update({
  id: '/ruhe',
  path: '/ruhe',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinenRoute = RoutinenRouteImport.update({
  id: '/routinen',
  path: '/routinen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EntscheidenRoute = EntscheidenRouteImport.update({
  id: '/entscheiden',
  path: '/entscheiden',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunWorkflowIdRoute = RunWorkflowIdRouteImport.update({
  id: '/run/$workflowId',
  path: '/run/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const RuheExerciseIdRoute = RuheExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => RuheRoute,
} as any)
const RoutinenNeuRoute = RoutinenNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => RoutinenRoute,
} as any)
const RoutinenWorkflowIdRoute = RoutinenWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => RoutinenRoute,
} as any)
const EntscheidenHelperIdRoute = EntscheidenHelperIdRouteImport.update({
  id: '/$helperId',
  path: '/$helperId',
  getParentRoute: () => EntscheidenRoute,
} as any)
const RoutinenBibliothekSlugRoute = RoutinenBibliothekSlugRouteImport.update({
  id: '/bibliothek/$slug',
  path: '/bibliothek/$slug',
  getParentRoute: () => RoutinenRoute,
} as any)
const RoutinenWorkflowIdBearbeitenRoute =
  RoutinenWorkflowIdBearbeitenRouteImport.update({
    id: '/bearbeiten',
    path: '/bearbeiten',
    getParentRoute: () => RoutinenWorkflowIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/entscheiden': typeof EntscheidenRouteWithChildren
  '/login': typeof LoginRoute
  '/routinen': typeof RoutinenRouteWithChildren
  '/ruhe': typeof RuheRouteWithChildren
  '/statistiken': typeof StatistikenRoute
  '/verbinden': typeof VerbindenRoute
  '/entscheiden/$helperId': typeof EntscheidenHelperIdRoute
  '/routinen/$workflowId': typeof RoutinenWorkflowIdRouteWithChildren
  '/routinen/neu': typeof RoutinenNeuRoute
  '/ruhe/$exerciseId': typeof RuheExerciseIdRoute
  '/run/$workflowId': typeof RunWorkflowIdRoute
  '/routinen/$workflowId/bearbeiten': typeof RoutinenWorkflowIdBearbeitenRoute
  '/routinen/bibliothek/$slug': typeof RoutinenBibliothekSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/entscheiden': typeof EntscheidenRouteWithChildren
  '/login': typeof LoginRoute
  '/routinen': typeof RoutinenRouteWithChildren
  '/ruhe': typeof RuheRouteWithChildren
  '/statistiken': typeof StatistikenRoute
  '/verbinden': typeof VerbindenRoute
  '/entscheiden/$helperId': typeof EntscheidenHelperIdRoute
  '/routinen/$workflowId': typeof RoutinenWorkflowIdRouteWithChildren
  '/routinen/neu': typeof RoutinenNeuRoute
  '/ruhe/$exerciseId': typeof RuheExerciseIdRoute
  '/run/$workflowId': typeof RunWorkflowIdRoute
  '/routinen/$workflowId/bearbeiten': typeof RoutinenWorkflowIdBearbeitenRoute
  '/routinen/bibliothek/$slug': typeof RoutinenBibliothekSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/entscheiden': typeof EntscheidenRouteWithChildren
  '/login': typeof LoginRoute
  '/routinen': typeof RoutinenRouteWithChildren
  '/ruhe': typeof RuheRouteWithChildren
  '/statistiken': typeof StatistikenRoute
  '/verbinden': typeof VerbindenRoute
  '/entscheiden/$helperId': typeof EntscheidenHelperIdRoute
  '/routinen/$workflowId': typeof RoutinenWorkflowIdRouteWithChildren
  '/routinen/neu': typeof RoutinenNeuRoute
  '/ruhe/$exerciseId': typeof RuheExerciseIdRoute
  '/run/$workflowId': typeof RunWorkflowIdRoute
  '/routinen/$workflowId/bearbeiten': typeof RoutinenWorkflowIdBearbeitenRoute
  '/routinen/bibliothek/$slug': typeof RoutinenBibliothekSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/einstellungen'
    | '/entscheiden'
    | '/login'
    | '/routinen'
    | '/ruhe'
    | '/statistiken'
    | '/verbinden'
    | '/entscheiden/$helperId'
    | '/routinen/$workflowId'
    | '/routinen/neu'
    | '/ruhe/$exerciseId'
    | '/run/$workflowId'
    | '/routinen/$workflowId/bearbeiten'
    | '/routinen/bibliothek/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/einstellungen'
    | '/entscheiden'
    | '/login'
    | '/routinen'
    | '/ruhe'
    | '/statistiken'
    | '/verbinden'
    | '/entscheiden/$helperId'
    | '/routinen/$workflowId'
    | '/routinen/neu'
    | '/ruhe/$exerciseId'
    | '/run/$workflowId'
    | '/routinen/$workflowId/bearbeiten'
    | '/routinen/bibliothek/$slug'
  id:
    | '__root__'
    | '/'
    | '/einstellungen'
    | '/entscheiden'
    | '/login'
    | '/routinen'
    | '/ruhe'
    | '/statistiken'
    | '/verbinden'
    | '/entscheiden/$helperId'
    | '/routinen/$workflowId'
    | '/routinen/neu'
    | '/ruhe/$exerciseId'
    | '/run/$workflowId'
    | '/routinen/$workflowId/bearbeiten'
    | '/routinen/bibliothek/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EinstellungenRoute: typeof EinstellungenRoute
  EntscheidenRoute: typeof EntscheidenRouteWithChildren
  LoginRoute: typeof LoginRoute
  RoutinenRoute: typeof RoutinenRouteWithChildren
  RuheRoute: typeof RuheRouteWithChildren
  StatistikenRoute: typeof StatistikenRoute
  VerbindenRoute: typeof VerbindenRoute
  RunWorkflowIdRoute: typeof RunWorkflowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verbinden': {
      id: '/verbinden'
      path: '/verbinden'
      fullPath: '/verbinden'
      preLoaderRoute: typeof VerbindenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiken': {
      id: '/statistiken'
      path: '/statistiken'
      fullPath: '/statistiken'
      preLoaderRoute: typeof StatistikenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruhe': {
      id: '/ruhe'
      path: '/ruhe'
      fullPath: '/ruhe'
      preLoaderRoute: typeof RuheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routinen': {
      id: '/routinen'
      path: '/routinen'
      fullPath: '/routinen'
      preLoaderRoute: typeof RoutinenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entscheiden': {
      id: '/entscheiden'
      path: '/entscheiden'
      fullPath: '/entscheiden'
      preLoaderRoute: typeof EntscheidenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$workflowId': {
      id: '/run/$workflowId'
      path: '/run/$workflowId'
      fullPath: '/run/$workflowId'
      preLoaderRoute: typeof RunWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruhe/$exerciseId': {
      id: '/ruhe/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/ruhe/$exerciseId'
      preLoaderRoute: typeof RuheExerciseIdRouteImport
      parentRoute: typeof RuheRoute
    }
    '/routinen/neu': {
      id: '/routinen/neu'
      path: '/neu'
      fullPath: '/routinen/neu'
      preLoaderRoute: typeof RoutinenNeuRouteImport
      parentRoute: typeof RoutinenRoute
    }
    '/routinen/$workflowId': {
      id: '/routinen/$workflowId'
      path: '/$workflowId'
      fullPath: '/routinen/$workflowId'
      preLoaderRoute: typeof RoutinenWorkflowIdRouteImport
      parentRoute: typeof RoutinenRoute
    }
    '/entscheiden/$helperId': {
      id: '/entscheiden/$helperId'
      path: '/$helperId'
      fullPath: '/entscheiden/$helperId'
      preLoaderRoute: typeof EntscheidenHelperIdRouteImport
      parentRoute: typeof EntscheidenRoute
    }
    '/routinen/bibliothek/$slug': {
      id: '/routinen/bibliothek/$slug'
      path: '/bibliothek/$slug'
      fullPath: '/routinen/bibliothek/$slug'
      preLoaderRoute: typeof RoutinenBibliothekSlugRouteImport
      parentRoute: typeof RoutinenRoute
    }
    '/routinen/$workflowId/bearbeiten': {
      id: '/routinen/$workflowId/bearbeiten'
      path: '/bearbeiten'
      fullPath: '/routinen/$workflowId/bearbeiten'
      preLoaderRoute: typeof RoutinenWorkflowIdBearbeitenRouteImport
      parentRoute: typeof RoutinenWorkflowIdRoute
    }
  }
}

interface EntscheidenRouteChildren {
  EntscheidenHelperIdRoute: typeof EntscheidenHelperIdRoute
}

const EntscheidenRouteChildren: EntscheidenRouteChildren = {
  EntscheidenHelperIdRoute: EntscheidenHelperIdRoute,
}

const EntscheidenRouteWithChildren = EntscheidenRoute._addFileChildren(
  EntscheidenRouteChildren,
)

interface RoutinenWorkflowIdRouteChildren {
  RoutinenWorkflowIdBearbeitenRoute: typeof RoutinenWorkflowIdBearbeitenRoute
}

const RoutinenWorkflowIdRouteChildren: RoutinenWorkflowIdRouteChildren = {
  RoutinenWorkflowIdBearbeitenRoute: RoutinenWorkflowIdBearbeitenRoute,
}

const RoutinenWorkflowIdRouteWithChildren =
  RoutinenWorkflowIdRoute._addFileChildren(RoutinenWorkflowIdRouteChildren)

interface RoutinenRouteChildren {
  RoutinenWorkflowIdRoute: typeof RoutinenWorkflowIdRouteWithChildren
  RoutinenNeuRoute: typeof RoutinenNeuRoute
  RoutinenBibliothekSlugRoute: typeof RoutinenBibliothekSlugRoute
}

const RoutinenRouteChildren: RoutinenRouteChildren = {
  RoutinenWorkflowIdRoute: RoutinenWorkflowIdRouteWithChildren,
  RoutinenNeuRoute: RoutinenNeuRoute,
  RoutinenBibliothekSlugRoute: RoutinenBibliothekSlugRoute,
}

const RoutinenRouteWithChildren = RoutinenRoute._addFileChildren(
  RoutinenRouteChildren,
)

interface RuheRouteChildren {
  RuheExerciseIdRoute: typeof RuheExerciseIdRoute
}

const RuheRouteChildren: RuheRouteChildren = {
  RuheExerciseIdRoute: RuheExerciseIdRoute,
}

const RuheRouteWithChildren = RuheRoute._addFileChildren(RuheRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EinstellungenRoute: EinstellungenRoute,
  EntscheidenRoute: EntscheidenRouteWithChildren,
  LoginRoute: LoginRoute,
  RoutinenRoute: RoutinenRouteWithChildren,
  RuheRoute: RuheRouteWithChildren,
  StatistikenRoute: StatistikenRoute,
  VerbindenRoute: VerbindenRoute,
  RunWorkflowIdRoute: RunWorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
